force-app/main/default/objects/Account/fields/fx_Status__c.field-meta.xml
<CustomField>
    <fullName>fx_Status__c</fullName>
    <description>Displaying the account Status.</description>
    <inlineHelpText>Displaying the account Status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Account_Contract__c/FX_Account_Contract__c.object-meta.xml
<CustomObject>
    <description>Contains the Contract records associated to the account.</description>
    <label>Account Contract</label>
    <nameField>
        <displayFormat>AC-{000}</displayFormat>
        <label>FX Account Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Account_Contract__c/fields/FX_Account__c.field-meta.xml
<CustomField>
    <fullName>FX_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Lookup field related to the Account Contract.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FX_Account_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FX_Account_Contract__c/fields/FX_Status__c.field-meta.xml
<CustomField>
    <fullName>FX_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Account_Contract_Clause__c/FX_Account_Contract_Clause__c.object-meta.xml
<CustomObject>
    <description>Contains the Clauses records associated to the Account Contract.</description>
    <label>Account Contract Clause</label>
    <nameField>
        <displayFormat>ACC-{000}</displayFormat>
        <label>Account Contract Clause Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contract Clause</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FX_Account_Contract_Clause__c/fields/FX_Account_Contract__c.field-meta.xml
<CustomField>
    <fullName>FX_Account_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Contract</label>
    <referenceTo>FX_Account_Contract__c</referenceTo>
    <relationshipLabel>Account Contract Clause</relationshipLabel>
    <relationshipName>Account_Contract_Clause</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FX_Account_Contract_Clause__c/fields/FX_Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>FX_Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Saint Barthélemy</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FX_Account_Contract_Clause__c/fields/FX_IsValid__c.field-meta.xml
<CustomField>
    <fullName>FX_IsValid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox will be checked if the Clause is valid for the respective contract</description>
    <inlineHelpText>Checkbox will be checked if the Clause is valid for the respective contract</inlineHelpText>
    <label>IsValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FX_AccountContractController.cls
public with sharing class FX_AccountContractController {
    

    // Wrapper class to send both data and errors
    public class ResponseWrapper {
        @AuraEnabled public List<FX_Account_Contract_Clause__c> data;
        @AuraEnabled public String error;
    }
    
    @AuraEnabled(cacheable=true)
    public static ResponseWrapper getAccountContractClauses(Id accountId) {

        ResponseWrapper response = new ResponseWrapper();
        
        try
        {

                if(accountId == null)
                {
                    
                    response.error = Label.fx_Account_Id_Missing;
                    return response; // Return response with error
           
                }
                
                //Fetch the Account details from the accountId
                
                Account acc = [Select BillingCountry from Account where Id =:accountId];
        
                //if the billingcountry is null it should sent back a response that as billingcountry is empty

                if (String.isBlank(acc.BillingCountry))
                {
                    response.error = Label.fx_Account_Billing_Country_Missing;
                    return response; // Return response with error
                }

                //fetch all associated Account Contract Clauses for the respective Account
                response.data = [Select Id,Name,FX_Account_Contract__r.Name,FX_Billing_Country__c,FX_IsValid__c 
                                                                                                                  FROM  FX_Account_Contract_Clause__c
                                                                                                                  WHERE FX_Account_Contract__c IN
                                                                                                                        (Select Id from FX_Account_Contract__c where FX_Account__c =:accountId)  ];
                //if the response data is missing
                if(response.data.size() == 0)
                {
                    response.error = Label.fx_Account_Contract_Clauses_Missing;
                    return response; // Return response with error
                }                                                                                                   
                
        } 
        catch (Exception e) {
            response.error = Label.fx_Unexpected_Error + e.getMessage();
        }
        
        return response;

    }

    @AuraEnabled
    public static void createAccountContracts(Id accountId, List<Id> clauseIds){
        try 
        {

            //insert the accountContract based on accountId
            FX_Account_Contract__c accountContract = new FX_Account_Contract__c(FX_Account__c=accountId,FX_Status__c ='Active');
            insert accountContract;
            System.debug('Account Contract Id:'+accountContract.Id);

            

            //Create a collection of AccountContractClauses to insert new records
            List<FX_Account_Contract_Clause__c> clausesToUpdate = new List<FX_Account_Contract_Clause__c>();

            List<String> clauseStringCollection = new List<String>();
            
            //looping through the existing clauses
            
            for(Id clauseId :clauseIds)
            {
                FX_Account_Contract_Clause__c clausetoUpdate = new FX_Account_Contract_Clause__c();
                clausetoUpdate.FX_Account_Contract__c = accountContract.Id;
                System.debug('Updated clause contract Id:'+clausetoUpdate.FX_Account_Contract__c );
                clausetoUpdate.id = clauseId;
                clausesToUpdate.add(clausetoUpdate);
               
            }

            //updating the clauses to the new contract created
            update clausesToUpdate;

            

            //save a copy of the displayed information as a file that is linked to Account Contract record

            List<FX_Account_Contract_Clause__c> clausesNameCollection = new List<FX_Account_Contract_Clause__c>([Select Name,FX_Account_Contract__r.Name,FX_Billing_Country__c,FX_IsValid__c from FX_Account_Contract_Clause__c where Id =:clauseIds]);
            for(FX_Account_Contract_Clause__c clause :clausesNameCollection)
            {
                clauseStringCollection.add(clause.Name+'--'+clause.FX_Account_Contract__r.Name+'--'+clause.FX_Billing_Country__c+'--'+clause.FX_IsValid__c);
            }
            String clauseText = String.join(clauseStringCollection, '\n');
            ContentVersion cv = new ContentVersion(
            Title = Label.fx_ClauseFileName,
            PathOnClient = 'ContractClauses.txt',
            VersionData = Blob.valueOf(clauseText),
            FirstPublishLocationId = accountContract.Id
            );
            insert cv;

            
            
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        
    }
}